{% set name = "lsstdesc-diffsky" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lsstdesc_diffsky-{{ version }}.tar.gz
  sha256: 09c49895eb48ee5142c6cfaded36f5f6ddfaa98997f7235c7d284a6817c7dc38

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=45
    - setuptools-scm >=7
    - tomli >=1.0.0
    - pip
  run:
    - python >=3.9
    - numpy
    - jax
    - h5py
    - diffmah
    - diffstar
    - dsps
    - diffsky

test:
  imports:
    - lsstdesc_diffsky
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/LSSTDESC/lsstdesc-diffsky
  summary: Library for differentiable generation of synthetic skies for LSST DESC
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - beckermr
