{% set name = "lsstdesc-diffsky" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lsstdesc_diffsky-{{ version }}.tar.gz
  sha256: f1ed6dcd155ee66be800d1ef1acf4312f755621b32fad0c8c70c0970df3e7c1f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.9
    - setuptools >=45
    - setuptools-scm >=7
    - tomli >=1.0.0
    - pip
  run:
    - python >=3.9
    - numpy
    - jax
    - numba
    - mpi4py
    - scipy
    - h5py
    - astropy-base
    - healpy
    - halotools
    - lsstdesc-galsampler
    - psutil
    - diffmah
    - diffstar
    - dsps
    - galsim
    - lsstdesc-gcr-catalogs

test:
  imports:
    - lsstdesc_diffsky
  # commands:
  #   # fails with "halotools 0.8.2 requires cython, which is not installed." so commented out
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://github.com/LSSTDESC/lsstdesc-diffsky
  summary: Library for differentiable generation of synthetic skies for LSST DESC
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - beckermr
